### ISSUE TITLE
pyomo version=5.3 missing py36 build for win-64 build

### ISSUE THREAD

**Issue by pedroreys** [conda-forge/pyomo-feedstock#37]
Hey folks, for pyomo version 5.3 the only available builds in conda-forge are:

| Build | Platform|
|---|---|
| py27_0| win-64|
| py27_0 | win-32|
|py36_0 | osx-64 |
|py36_0| linux-64|
<br/>
Any chance of getting a `py36_0` build in conda-forge of pyomo 5.3 for `win-64` and `win-32`?

Thanks in advance.

**Comment by blnicho** [comment]
Pyomo 5.3 is over 2 years old. May I ask why you need that version instead of a more recent release?

**Comment by pedroreys** [comment]
Sure, I'm working on getting that updated. But currently in production we have that version pinned and I can't setup a local windows dev environment to match what we have in production. It works on my mac and on my linux boxes, but not on my colleagues windows machines.

For now we were able to work around this by installing that pyomo version via pip instead of conda, but I decided to ask if it was possible to get that py36_0 build for win-64 published anyway :)

**Comment by blnicho** [comment]
@pedroreys unfortunately I don't know enough about conda-forge to build/rebuild the conda package for an old version and I don't think anyone on the Pyomo team will have time to look into this in the near future. We build the conda package as part of our release process and have never had to go back and modify an old version. I'm also concerned that you could run into package dependency issues trying to build such an old version of Pyomo especially if you're using any of the Pyomo extensions that require numpy, scipy, etc. (we have fixed several deprecation/compatibility issues with these packages in the last 2 years). @jsiirola @whart222 any thoughts on this request?

My recommendation would be to move to a newer version of Pyomo at the earliest opportunity and until then you've already found the best work around by installing with pip instead.

**Comment by pedroreys** [comment]
Thanks for the response @blnicho.
